name: the_market
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  bloc: ^8.1.4
  dio: ^5.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  google_fonts: 6.1.0
  ionicons: ^0.2.2
  solar_icons: ^0.0.5
  meta: ^1.9.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  enefty_icons: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/  



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/ic_launcher (1).png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/ic_launcher (1).png"
    background_color: "#48D861"
    theme_color: "#F1F1FF"
  windows:
    generate: true
    image_path: "lib/assets/ic_launcher (1).png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/ic_launcher.png"